<?php

namespace AppBundle\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    public function createFindAllQuery()
    {
        $this->_em->getRepository("AppBundle:Blog")->createQueryBuilder('b');
    }

}
