<?php

namespace AppBundle\Repository;

/**
 * TvshowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvshowRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTvshowsByUserId($id)
    {
        $qb = $this->createQueryBuilder('b')
            ->where('b.userId=:id')
            ->setParameter('id', $id);

        return $qb->getQuery();
    }
}
